### ISSUE TITLE
How config to run in mongo replicaset?

### ISSUE THREAD

**Issue by giaosudau** [Stratio/Spark-MongoDB#101]
For example.
I have a replicaset name 'giaosudau_db' and three mongo server host1:27017, host2:27017, host3:27017
How to config in code?
`MongodbConfigBuilder(Map(Host -> List("host1:27017","host2:27017", "host3:27017"),
        Database -> rawDB,
        Collection -> pageViewColl))`
Because If I only put host1:27017 for connection
`MongodbConfigBuilder(Map(Host -> List("host1:27017"),
        Database -> rawDB,
        Collection -> pageViewColl))`
It throws me a GCOveread error.

**Comment by pmadrigal** [comment]
Hi  @giaosudau ,

Configuration is correct if you are using 'fromMongodb' method to read:

```
val mongoRDD = sqlContext.fromMongoDB(readConfig)
mongoRDD.registerTempTable("pageViewColl")
```
You should check this document to ensure a correct connection:
https://github.com/Stratio/spark-mongodb/blob/master/doc/src/site/sphinx/faqs.rst

**Comment by giaosudau** [comment]
but when I run I got error
`16/02/24 00:35:48 INFO TaskSetManager: Finished task 70.0 in stage 12.0 (TID 1319) in 4016 ms on localhost (68/200)`

`16/02/24 00:30:01 INFO ShuffleBlockFetcherIterator: Getting 97 non-empty blocks out of 200 blocks`
`16/02/24 00:30:01 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms`
`16/02/24 00:30:04 INFO UnsafeExternalSorter: Thread 138 spilling sort data of 34.0 MB to disk (0  time so far)`
`16/02/24 00:30:24 INFO cluster: Setting max election id to 56cc7d96ab56224f6b311a93 from replica set primary host1:27017`
`16/02/24 00:40:23 INFO ShuffleBlockFetcherIterator: Getting 1 non-empty blocks out of 1 blocks`
`16/02/24 00:40:26 ERROR Executor: Exception in task 36.0 in stage 12.0 (TID 1285)
java.io.FileNotFoundException: /tmp/blockmgr-f8159f36-57a6-4b18-8377-ed8caedc0b0a/01/temp_shuffle_ea3e0547-e05e-4174-8864-6c5374a49643 (No such file or directory)`

`ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker-0,5,main]
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.apache.spark.unsafe.types.UTF8String.fromAddress(UTF8String.java:94)
	at org.apache.spark.sql.catalyst.expressions.UnsafeRow.getUTF8String(UnsafeRow.java:403)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificOrdering.compare(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.codegen.BaseOrdering.compare(GenerateOrdering.scala:28)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter$RowComparator.compare(UnsafeExternalRowSorter.java:202)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeSorterSpillMerger$1.compare(UnsafeSorterSpillMerger.java:39)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeSorterSpillMerger$1.compare(UnsafeSorterSpillMerger.java:32)
	at java.util.PriorityQueue.siftDownUsingComparator(PriorityQueue.java:699)
	at java.util.PriorityQueue.siftDown(PriorityQueue.java:667)
	at java.util.PriorityQueue.poll(PriorityQueue.java:578)
	at java.util.AbstractQueue.remove(AbstractQueue.java:113)
	at org.apache.spark.util.collection.unsafe.sort.UnsafeSorterSpillMerger$2.loadNext(UnsafeSorterSpillMerger.java:83)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter$1.next(UnsafeExternalRowSorter.java:142)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter$1.next(UnsafeExternalRowSorter.java:129)
	at org.apache.spark.sql.execution.RowIteratorFromScala.advanceNext(RowIterator.scala:84)
	at org.apache.spark.sql.execution.joins.SortMergeJoinScanner.advancedStreamed(SortMergeJoin.scala:303)
	at org.apache.spark.sql.execution.joins.SortMergeJoinScanner.findNextInnerJoinRows(SortMergeJoin.scala:210)
	at org.apache.spark.sql.execution.joins.SortMergeJoin$$anonfun$doExecute$1$$anon$1.advanceNext(SortMergeJoin.scala:129)
	at org.apache.spark.sql.execution.RowIteratorToScala.hasNext(RowIterator.scala:68)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.sql.execution.Aggregate$$anonfun$doExecute$1$$anonfun$7.apply(Aggregate.scala:162)
	at org.apache.spark.sql.execution.Aggregate$$anonfun$doExecute$1$$anonfun$7.apply(Aggregate.scala:157)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
`
`6/02/24 00:48:09 ERROR MapOutputTrackerMaster: Error communicating with MapOutputTracker
java.lang.NullPointerException
	at org.apache.spark.MapOutputTracker.askTracker(MapOutputTracker.scala:109)
	at org.apache.spark.MapOutputTracker.getMapSizesByExecutorId(MapOutputTracker.scala:167)
	at org.apache.spark.shuffle.hash.HashShuffleReader.read(HashShuffleReader.scala:47)
	at org.apache.spark.sql.execution.ShuffledRowRDD.compute(ShuffledRowRDD.scala:71)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsWithPreparationRDD.compute(MapPartitionsWithPreparationRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.ZippedPartitionsRDD2.compute(ZippedPartitionsRDD.scala:99)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by pmadrigal** [comment]
@giaosudau it looks like a spark memory problem, it doesn't comes from our project.

Try to increase memory in your spark cluster.

**Comment by giaosudau** [comment]
Thanks.
BTW @pmadrigal If I process for 8GB mongo data.
How much RAM it will set can you give me how we estimate the RAM for processing?

**Comment by pmadrigal** [comment]
@giaosudau you should try increasing memory and using some config params, take a look  to spark documentation:

http://spark.apache.org/docs/latest/hardware-provisioning.html

http://spark.apache.org/docs/latest/tuning.html


I hope you can solve your problem!

**Comment by giaosudau** [comment]
Thank you @pmadrigal
