### ISSUE TITLE
com.mongodb.MongoException: host and port should be specified in host:port format

### ISSUE THREAD

**Issue by ziapapa** [Stratio/Spark-MongoDB#140]
The JAVA API were tested.

mongodb STANDALONE when normal
mongodb SHARDED only when an error occurs

But the output value is the same as STANDALONE
(Only error occurs and the data is no problem)
What 's this?
It changed the source code changed only DB IP

`options.put ( "host", "localip: 27017");
==> Options.put ( "host", "mongos_ip: 27017");`

Error message below.

`[ERROR] [05/18/2016 14:59:24.498] [default-akka.actor.default-dispatcher-2] [akka://default/user/mongoConnectionActor] host and port should be specified in host:port format
com.mongodb.MongoException: host and port should be specified in host:port format
at com.mongodb.ServerAddress.<init>(ServerAddress.java:122)
at com.mongodb.ServerAddress.<init>(ServerAddress.java:49)
at com.stratio.datasource.mongodb.client.MongodbClientActor.com$stratio$datasource$mongodb$client$MongodbClientActor$$doGetClient(MongodbClientActor.scala:108)
at com.stratio.datasource.mongodb.client.MongodbClientActor$$anonfun$receive$1.applyOrElse(MongodbClientActor.scala:45)
at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
at com.stratio.datasource.mongodb.client.MongodbClientActor.aroundReceive(MongodbClientActor.scala:34)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
at akka.actor.ActorCell.invoke(ActorCell.scala:487)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
at akka.dispatch.Mailbox.run(Mailbox.scala:220)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

**Comment by johnnydepup** [comment]
Did you find a fix for the error?
