### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by DiegoRam** [Stratio/spark-mongodb#33]
Hey guys, I created a simple program with SBT and Scala. So I cloned this project and published it locally.

Since this is a maven project I added this line to my SBT build file

*resolvers += Resolver.mavenLocal*

Although I already have Casbah as an Ivy dependency solved I'm getting this error.

Error:Error while importing SBT project:
...
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] sbt.ResolveException: unresolved dependency: org.mongodb#casbah-commons_${scala.binary.version};2.8.0: not found
[error] unresolved dependency: org.mongodb#casbah-query_${scala.binary.version};2.8.0: not found
[error] unresolved dependency: org.mongodb#casbah-core_${scala.binary.version};2.8.0: not found
[error] Use 'last' for the full log.

Any idea?

**Comment by pmadrigal** [comment]
Hi!

There is a PR #38 to solve this problem. Now only it works correctly for scala 2.10, if you need scala 2.11 use the profile and change scala properties in the pom.

We are working in automatize this.

Thanks for your feedback :)
