### ISSUE TITLE
user & pwd

### ISSUE THREAD

**Issue by nirby82** [Stratio/spark-mongodb#42]
Hi,

when I connect to mongodb from terminal I pass User, Password and AuthenticationDatabase

how can i pass these arguments through this connector?

thanks

**Comment by pmadrigal** [comment]
Hi!

You have to set the required parameters:
* host
* database
* collection

Moreover, in your special case you have to set credential parameter.

So, your builder should be as follows:

```scala
val builder = MongodbConfigBuilder(Map(Host -> List("localhost:27017"), Database -> "databaseName", Collection -> "collectionName", Credentials -> "user,database,password"))
val readConfig = builder.build()
```
if you have a big collection and you know the collection schema, it is better to use it, else, add a small SamplingRatio to the builder. 

For small collections this doesn't matter.

You can see complete examples in our [documentation](https://github.com/Stratio/spark-mongodb/blob/master/doc/src/site/sphinx/First_Steps.rst).

**Comment by nirby82** [comment]
thanks

seems like a connection was made because i am no longer getting a connection error.
now I am receiving this error: 
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to scala.collection.TraversableLike
	at com.stratio.provider.mongodb.partitioner.MongodbPartitioner.<init>(MongodbPartitioner.scala:42)
	at com.stratio.provider.mongodb.MongodbRelation.<init>(MongodbRelation.scala:51)
	at com.stratio.provider.mongodb.MongodbContext.fromMongoDB(mongodbFunctions.scala:43)
	at mongodb$.main(mongodb.scala:43)
	at mongodb.main(mongodb.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by pmadrigal** [comment]
Which version of our project are you using?

**Comment by nirby82** [comment]
0.9.0

**Comment by pmadrigal** [comment]
Sorry but i can't reproduce your error, credentials are working for me.

Let me know more about your code.

Are you using master branch, right?

This is a simple example using credentials with java, and works for me:

```java
public class Mongo {

    public static void main(String[] args) {

        JavaSparkContext sc = new JavaSparkContext("local[2]", "test mongo java"); // An existing JavaSparkContext.
        SQLContext sqlContext = new org.apache.spark.sql.SQLContext(sc);
        Map options = new HashMap();
        options.put("host", "localhost:27017");
        options.put("database", "highschoolCredentials");
        options.put("collection", "students");
        options.put("credentials", "user,highschoolCredentials,password");

        DataFrame df = sqlContext.read().format("com.stratio.provider.mongodb").options(options).load();
        df.show();

    }
}
```
