### ISSUE TITLE
credentials conf not working

### ISSUE THREAD

**Issue by anand-singh** [Stratio/Spark-MongoDB#68]
```
Credentials -> "anand-singh,spark-mongo-1,anand-singh"
```

```
[error] - com.rklick.engine.contexts.MongoContext$ - java.lang.String cannot be cast to scala.collection.immutable.List
java.lang.ClassCastException: java.lang.String cannot be cast to scala.collection.immutable.List
	at com.stratio.datasource.mongodb.partitioner.MongodbPartitioner.<init>(MongodbPartitioner.scala:41) ~[spark-mongodb_2.11-0.10.1.jar:na]
	at com.stratio.datasource.mongodb.MongodbRelation.<init>(MongodbRelation.scala:48) ~[spark-mongodb_2.11-0.10.1.jar:na]
	at com.stratio.datasource.mongodb.MongodbContext.fromMongoDB(mongodbFunctions.scala:40) ~[spark-mongodb_2.11-0.10.1.jar:na]
	at com.rklick.engine.contexts.MongoContext$class.toDataFrame(MongoContext.scala:56) ~[classes/:na]
	at com.rklick.engine.contexts.MongoContext$.toDataFrame(MongoContext.scala:69) [classes/:na]
	at com.rklick.engine.contexts.MongoTestContext$.main(MongoContext.scala:78) [classes/:na]
	at com.rklick.engine.contexts.MongoTestContext.main(MongoContext.scala) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at sbt.Run.invokeMain(Run.scala:67) [run-0.13.9.jar:0.13.9]
	at sbt.Run.run0(Run.scala:61) [run-0.13.9.jar:0.13.9]
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51) [run-0.13.9.jar:0.13.9]
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55) [run-0.13.9.jar:0.13.9]
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55) [run-0.13.9.jar:0.13.9]
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55) [run-0.13.9.jar:0.13.9]
	at sbt.Logger$$anon$4.apply(Logger.scala:85) [logging-0.13.9.jar:0.13.9]
	at sbt.TrapExit$App.run(TrapExit.scala:248) [run-0.13.9.jar:0.13.9]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
com.rklick.utils.exception.DataFrameLoadException: java.lang.String cannot be cast to scala.collection.immutable.List

```

**Comment by anand-singh** [comment]
Hi Dev Team,

It is working now for me but i have to set credentials same like below:

```
Credentials -> List(com.stratio.datasource.mongodb.MongodbCredentials(user, database, password.toCharArray))
```

Please look into this ASAP

Thanks,
Anand

**Comment by pmadrigal** [comment]
Hi @anand-singh,

You are right, this is the correct way if you are using MongodbConfigBuilder, but if you are using SQL to create the table, you need to set credentials in string format.

We will update the documentation.

Thanks for your feedback!

**Comment by pmadrigal** [comment]
Doc updated in branch 0.11
