### ISSUE TITLE
Integration with Spark 1.4

### ISSUE THREAD

**Issue by gserranojc** [Stratio/spark-mongodb#9]
Now, I can create a temporal table and insert values with the next code:

```
val saveConfig = MongodbConfigBuilder(Map(Host -> List("localhost:27017"), Database -> EsIndex, Collection ->
     EsMapping, SamplingRatio -> 1.0, WriteConcern -> MongodbWriteConcern.Unacknowledged,     SplitSize -> 8, SplitKey -> "_id",
      SplitSize -> 8, SplitKey -> "_id"))

dfMongo.saveToMongodb(saveConfig.build)

val readConfig = saveConfig.build()
val mongoRDD = hContext.fromMongoDB(readConfig)
mongoRDD.registerTempTable("testMongo")

```

The new write mode for dataSources generate errors:

```
dfMongo.write.format("com.stratio.provider.mongodb").mode(SaveMode.Append).options(
      Map("host" -> "localhost:27017", "database" -> "testmongo", "collection" -> "realtime")).save()

Exception in thread "main" java.lang.RuntimeException: com.stratio.provider.mongodb.DefaultSource does not allow create table as select.
	at scala.sys.package$.error(package.scala:27)
	at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:335)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:144)
	at com.utad.url.HttpStreamProcessing$.main(HttpStreamProcessing.scala:120)
	at com.utad.url.HttpStreamProcessing.main(HttpStreamProcessing.scala)

```
The  new functions for createExternalTable generate one error in the table creation:

```
    hContext.createExternalTable("tmongo", "com.stratio.provider.mongodb", schemaMongo, Map("host" ->
      "localhost:27017",
      "database" -> EsIndex, "collection" -> EsMapping))

Exception in thread "main" org.spark-project.guava.util.concurrent.UncheckedExecutionException: org.apache.spark.sql.AnalysisException: com.stratio.provider.mongodb.DefaultSource does not allow user-specified schemas.;
	at org.spark-project.guava.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4882)
	at org.spark-project.guava.cache.LocalCache$LocalLoadingCache.apply(LocalCache.java:4898)
	at org.apache.spark.sql.hive.HiveMetastoreCatalog.lookupRelation(HiveMetastoreCatalog.scala:231)

```

The sql function for create tables in Hive Context fails when execute any query:

```
    hContext.sql(
      s"""CREATE TABLE IF NOT EXISTS testMongo(
         |  id STRING)
         |USING com.stratio.provider.mongodb
         |OPTIONS (
         |  host 'localhost:27017', database '${EsIndex}', collection '${EsMapping}'
         | )
      """.stripMargin)

    val queryMongo = hContext.sql(s"SELECT id FROM testMongo")
    queryMongo.collect().foreach(r => print(r.toString()))
    println("Mongo Count: " + queryMongo.count())

Exception in thread "main" org.spark-project.guava.util.concurrent.UncheckedExecutionException: org.apache.spark.sql.AnalysisException: com.stratio.provider.mongodb.DefaultSource does not allow user-specified schemas.;
	at org.spark-project.guava.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4882)
	at org.spark-project.guava.cache.LocalCache$LocalLoadingCache.apply(LocalCache.java:4898)
	at org.apache.spark.sql.hive.HiveMetastoreCatalog.lookupRelation(HiveMetastoreCatalog.scala:231)

```

**Comment by pmadrigal** [comment]
This is updated in master. Will be in Central Maven in next days.

Thank you very much for your feedback!

**Comment by pmadrigal** [comment]
It is already in Central Maven. Version 0.8.6.

Thank you very much!
